version: ""

services:
  postgress:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: leodev
      POSTGRES_PASSWORD: leo123456
      POSTGRES_DB: school
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: nextjs_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL: postgresql://leodev:leo123456@localhost:5432/school?schema=public
    depends_on:
      - postgres

volumes:
  postgres_data:
